### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by qianwang102** [islamaymansais/Botnet-Detection-Deep-Autoencoders#3]
Did this project use the N_BaIoT dataset? 
How the dataset.csv generated? 
Could you provide the .ipynb file?
Looking forward to your reply.

**Comment by islamaymansais** [comment]
Hi Qian, 

I don't have the .ipynb file on me handy. I can try to dig it up but will take a while. However, here is the link to the [dataset.csv].

I wrote a quick script to generate the CSV (also need to dig that up for you). But essentially, the way the script worked was that it:

1. Downloaded the N_BaIoT dataset
2. Merged all the malicious records together and assigned a target label of 1
3. Merged all the healthy records together and assigned a target label of 0
4. Merged all the records together to create dataset.csv

I need to push a new version of this code. I've been able to reproduce some of the results discussed in the paper, but I think my model could be overfit (which is what is preventing me from pushing a new version at the moment). If you are also implementing this and was able to reproduce the results, can you also share a link to your repo, please? Would love to see how you reached those results. Thanks in advance!

Let me know if you're not able to access the link.

(https://drive.google.com/file/d/1OAsVm3O3BO7PoxbSO4hMC0MAdQ4U-VVK/view?usp=sharing)

**Comment by qianwang102** [comment]
Thanks for your sharing! I can reach the dataset you provided.
This is my research direction but i am just a beginner .I will try to reproduce the result, but it will take time.
If I got some result, I will share it with you.
Good luck to your study and life!

**Comment by qianwang102** [comment]
> 
> 
> Hi Qian,
> 
> I don't have the .ipynb file on me handy. I can try to dig it up but will take a while. However, here is the link to the [dataset.csv] (https://drive.google.com/file/d/1OAsVm3O3BO7PoxbSO4hMC0MAdQ4U-VVK/view?usp=sharing).
> 
> I wrote a quick script to generate the CSV (also need to dig that up for you). But essentially, the way the script worked was that it:
> 
>     1. Downloaded the N_BaIoT dataset
> 
>     2. Merged all the malicious records together and assigned a target label of 1
> 
>     3. Merged all the healthy records together and assigned a target label of 0
> 
>     4. Merged all the records together to create dataset.csv
> 
> 
> I need to push a new version of this code, but haven't got the time to do so yet. I've been able to reproduce some of the results discussed in the paper, but I think my model could be overfit (which is what is preventing me from pushing a new version at the moment). If you are also implementing this and was able to reproduce the results, can you also share a link to your repo, please? Would love to see how you reached those results. Thanks in advance!
> 
> Let me know if you're not able to access the link.



> 
> 
> Hi Qian,
> 
> I don't have the .ipynb file on me handy. I can try to dig it up but will take a while. However, here is the link to the [dataset.csv] (https://drive.google.com/file/d/1OAsVm3O3BO7PoxbSO4hMC0MAdQ4U-VVK/view?usp=sharing).
> 
> I wrote a quick script to generate the CSV (also need to dig that up for you). But essentially, the way the script worked was that it:
> 
>     1. Downloaded the N_BaIoT dataset
> 
>     2. Merged all the malicious records together and assigned a target label of 1
> 
>     3. Merged all the healthy records together and assigned a target label of 0
> 
>     4. Merged all the records together to create dataset.csv
> 
> 
> I need to push a new version of this code, but haven't got the time to do so yet. I've been able to reproduce some of the results discussed in the paper, but I think my model could be overfit (which is what is preventing me from pushing a new version at the moment). If you are also implementing this and was able to reproduce the results, can you also share a link to your repo, please? Would love to see how you reached those results. Thanks in advance!
> 
> Let me know if you're not able to access the link.

Thanks for your sharing! I can reach the dataset you provided.
This is my research direction but i am just a beginner .I will try to reproduce the result, but it will take time.
If I got some result, I will share it with you.
Good luck to your study and life!

**Comment by qianwang102** [comment]
> 
> 
> Hi Qian,
> 
> I don't have the .ipynb file on me handy. I can try to dig it up but will take a while. However, here is the link to the [dataset.csv] (https://drive.google.com/file/d/1OAsVm3O3BO7PoxbSO4hMC0MAdQ4U-VVK/view?usp=sharing).
> 
> I wrote a quick script to generate the CSV (also need to dig that up for you). But essentially, the way the script worked was that it:
> 
>     1. Downloaded the N_BaIoT dataset
> 
>     2. Merged all the malicious records together and assigned a target label of 1
> 
>     3. Merged all the healthy records together and assigned a target label of 0
> 
>     4. Merged all the records together to create dataset.csv
> 
> 
> I need to push a new version of this code, but haven't got the time to do so yet. I've been able to reproduce some of the results discussed in the paper, but I think my model could be overfit (which is what is preventing me from pushing a new version at the moment). If you are also implementing this and was able to reproduce the results, can you also share a link to your repo, please? Would love to see how you reached those results. Thanks in advance!
> 
> Let me know if you're not able to access the link.

Thanks for your sharing! I can reach the dataset you provided.
This is my research direction but i am just a beginner .I will try to reproduce the result, but it will take time.
If I got some result, I will share it with you.
Good luck to your study and life!

**Comment by islamaymansais** [comment]
No worries take your time and best of luck in your studies. It's definitely a very exciting field with very hot future career prospects! Btw can you start this repo? :D
